title: All Things PG
description: Public documentation for Phase 2 of All Things PG
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - docs/index.md
exclude:
  - home/home.md
gateway:
  allow_blank_development: false
defaults:
  - scope:
      path: ""
    values:
      layout: page
